spring.application.name=Public-Grievance-Redressal-Portal

spring.datasource.url=jdbc:postgresql://${SUPABASE_DB_HOST:db.amkdvmpkepfpgydrwcdo.supabase.co}:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${SUPABASE_DB_PASSWORD:pratapsakthivel1s23}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET:PublicGrievanceRedressalPortalSuperSecretJWTKey2026Secure32BytePlus!}
app.jwt.expiration-ms=86400000
